version: '3.8'

services:
  redis:
    image: ahmarhashmi1991/redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  heartbeat:
    image: busybox:latest
    volumes:
      - ~/.ssh:/root/.ssh  # Mount the local SSH keys directory to the container
    command: >
      sh -c 'while true; do echo "Heartbeat from redis" | nc -w 1 -u -v 20.244.90.49 22 -i ./ahmar-dev_key.pem azureuser@20.244.90.49; sleep 15; done'
