version: '3.8'

x-docker-config:
  auth: "=="
YWhtYXIuaGFzaG1pMTk5MUBnbWFpbC5jb206aGFtbXlASUlUQjEyMw
services:
  nginx:
    image: ahmarhashmi1991/nginx
    container_name: nginx
    restart: always
    ports:
      - "8000:8000"
