version: '3.8'

x-docker-config:
  auth: "YWhtYXIuaGFzaG1pMTk5MUBnbWFpbC5jb206aGFtbXlASUlUQjEyMw=="

services:
  redis:
    image: ahmarhashmi1991/redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
